server:
  port: 3000
spring:
  cloud:
    config:
      server:
        git:
          default-label: main
          uri: https://github.com/Design-Tech-UPC/Legiz-Config-Data.git
    application:
      name: config-service
